web:
  build: ./web
  container_name: api-supfile
  volumes:
    - ./web:/src
  expose:
    - 80
  ports:
      - 8080:80
  links:
    - db
  command: npm start

db:
  image: mongo
  container_name: api-supfile-db
  expose:
    - 27017

mongo-express:
  image: mongo-express
  container_name: api-supfile-mongo-express
  ports:
    - 8081:8081
  environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME='admin'
    - ME_CONFIG_MONGODB_ADMINPASSWORD='admin'
    - ME_CONFIG_BASICAUTH_USERNAME=eviato
    - ME_CONFIG_BASICAUTH_PASSWORD=Supinf0!
  links:
    - db:mongo
