web:
  image: supfile-api:v1.0
  ports:
      - 80:80
  links:
    - db

db:
  image: mongo
  container_name: api-supfile-db
  expose:
    - 27017

mongo-express:
  image: mongo-express
  container_name: api-supfile-mongo-express
  ports:
    - 81:8081
  environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME='admin'
    - ME_CONFIG_MONGODB_ADMINPASSWORD='admin'
    - ME_CONFIG_BASICAUTH_USERNAME=eviato
    - ME_CONFIG_BASICAUTH_PASSWORD=Supinf0!
  links:
    - db:mongo
