apiVersion: v1
kind: Service
metadata:
  labels:
    name: service-api
  name: service-api
spec:
  ports:
    - port: 80
  selector:
    app: pod-api
  clusterIP: None
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-api
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "3"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 50G
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy-api
  labels:
    app: deploy-api
spec:
  replicas: 1
  serviceName: "service-api"
  selector:
    matchLabels:
      app: pod-api
  template:
    metadata:
      labels:
        app: pod-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: api-pods
        image: eviato/supfile-api:2.5
        ports:
          - containerPort: 80
        volumeMounts:
          - name: datadir
            mountPath: /src/app/public/files
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      storageClassName: openebs-api
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50G
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: backend.lmaj.tk
    http:
      paths:
      - backend:
          serviceName: service-api
          servicePort: 80
  tls:
  - secretName: api-secret
    hosts:
    - backend.lmaj.tk
