apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  labels:
    app: deploy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-app
  template:
    metadata:
      labels:
        app: pod-app
    spec:
      containers:
      - name: app-pods
        image: eviato/supfile-app:2.0
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: service-app
  name: service-app
spec:
  ports:
    - port: 80
  selector:
    app: pod-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: supfile.lmaj.tk
    http:
      paths:
      - backend:
          serviceName: service-app
          servicePort: 80
  tls:
  - secretName: app-secret
    hosts:
    - supfile.lmaj.tk
